"""
Django settings for lk project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_list(value):
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-u^8jk*-tm6(!hy!*^swkm6#c%!0l=)z6!*8)h3z((vxtr4+5p8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=csv_list)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=csv_list)
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'money'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'money.middleware.OneCSyncRequestMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='djangolk'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432', cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', 
    default='http://localhost:8080,http://localhost:3000',
    cast=csv_list
)

AI_DEFAULT_PROVIDER = config('AI_DEFAULT_PROVIDER', default='openrouter')
AI_OPENROUTER_API_KEY = config('AI_OPENROUTER_API_KEY', default='')
AI_OPENROUTER_MODEL = config('AI_OPENROUTER_MODEL', default='google/gemini-2.5-flash')
AI_OPENROUTER_BASE_URL = config(
    'AI_OPENROUTER_BASE_URL',
    default='https://openrouter.ai/api/v1/chat/completions',
)
AI_OPENROUTER_SITE_URL = config('AI_OPENROUTER_SITE_URL', default='')
AI_OPENROUTER_APP_NAME = config('AI_OPENROUTER_APP_NAME', default='djangolk')
AI_OPENAI_API_KEY = config('AI_OPENAI_API_KEY', default='')
AI_OPENAI_TRANSCRIBE_MODEL = config('AI_OPENAI_TRANSCRIBE_MODEL', default='gpt-4o-mini-transcribe')
AI_OPENAI_TRANSCRIBE_BASE_URL = config(
    'AI_OPENAI_TRANSCRIBE_BASE_URL',
    default='https://api.openai.com/v1/audio/transcriptions',
)
AI_OPENAI_TRANSCRIBE_LANGUAGE = config('AI_OPENAI_TRANSCRIBE_LANGUAGE', default='ru')
AI_OPENAI_TRANSCRIBE_PROMPT = config('AI_OPENAI_TRANSCRIBE_PROMPT', default='')
AI_ALLOW_RULE_BASED_FALLBACK = config('AI_ALLOW_RULE_BASED_FALLBACK', default=True, cast=bool)
AI_TELEGRAM_BOT_SECRET = config('AI_TELEGRAM_BOT_SECRET', default='')
AI_TELEGRAM_BOT_TOKEN = config('AI_TELEGRAM_BOT_TOKEN', default='')
AI_TELEGRAM_API_BASE_URL = config('AI_TELEGRAM_API_BASE_URL', default='https://api.telegram.org')
AI_DUPLICATE_WINDOW_SECONDS = config('AI_DUPLICATE_WINDOW_SECONDS', default=600, cast=int)

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

# Spectacular API docs settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'LK API',
    'DESCRIPTION': 'Автоматически сгенерированная документация REST API',
    'VERSION': '1.0.0',
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'UserStatusEnum': [
            ('COMP', 'Компания'),
            ('PRIV', 'Частное лицо'),
        ],
        'AiAssistantStatusEnum': [
            'created',
            'preview',
            'needs_confirmation',
            'balance',
            'duplicate',
        ],
        'AiProcessedInputStatusEnum': [
            ('created', 'Created'),
            ('duplicate', 'Duplicate'),
        ],
    },
}
