"""
Django settings for lk project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from urllib.parse import urlsplit
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def csv_list(value):
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOW_INSECURE_SETTINGS = config('DJANGO_ALLOW_INSECURE_SETTINGS', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
_DEFAULT_SECRET_KEY = 'django-insecure-dev-only-change-me'
SECRET_KEY = config('SECRET_KEY', default=_DEFAULT_SECRET_KEY)
if not DEBUG and not ALLOW_INSECURE_SETTINGS and SECRET_KEY == _DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG=False.')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=csv_list)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=csv_list)
if not DEBUG and not ALLOW_INSECURE_SETTINGS:
    if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured('ALLOWED_HOSTS must be explicit when DEBUG=False.')
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured('CSRF_TRUSTED_ORIGINS must be set when DEBUG=False.')

USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='same-origin')
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax')
AUTH_ACCESS_COOKIE_NAME = config('AUTH_ACCESS_COOKIE_NAME', default='money_access')
AUTH_REFRESH_COOKIE_NAME = config('AUTH_REFRESH_COOKIE_NAME', default='money_refresh')
AUTH_SESSION_COOKIE_NAME = config('AUTH_SESSION_COOKIE_NAME', default='money_session')
AUTH_COOKIE_SECURE = config('AUTH_COOKIE_SECURE', default=not DEBUG, cast=bool)
AUTH_COOKIE_SAMESITE = config('AUTH_COOKIE_SAMESITE', default='Lax')
AUTH_COOKIE_PATH = config('AUTH_COOKIE_PATH', default='/')

APP_DOMAIN = config(
    'APP_DOMAIN',
    default=ALLOWED_HOSTS[0] if ALLOWED_HOSTS else 'localhost',
)
_MCP_LOOPBACK_HOSTS = {'localhost', '127.0.0.1', '::1'}
_MCP_EXTERNAL_HOST = urlsplit(f'//{APP_DOMAIN}').hostname
_MCP_EXTERNAL_SCHEME = 'http' if _MCP_EXTERNAL_HOST in _MCP_LOOPBACK_HOSTS else 'https'
_MCP_DEFAULT_ISSUER_URL = f'{_MCP_EXTERNAL_SCHEME}://{APP_DOMAIN}'
MCP_ISSUER_URL = config('MCP_ISSUER_URL', default=_MCP_DEFAULT_ISSUER_URL).rstrip('/')
MCP_PUBLIC_URL = config('MCP_PUBLIC_URL', default=f'{MCP_ISSUER_URL}/mcp').rstrip('/')
MCP_BACKEND_URL = config('MCP_BACKEND_URL', default='http://127.0.0.1:8000').rstrip('/')
MCP_OAUTH_ALLOWED_REDIRECT_ORIGINS = config(
    'MCP_OAUTH_ALLOWED_REDIRECT_ORIGINS',
    default='',
    cast=csv_list,
)
MCP_OAUTH_ACCESS_TOKEN_SECONDS = config('MCP_OAUTH_ACCESS_TOKEN_SECONDS', default=900, cast=int)
MCP_OAUTH_REFRESH_TOKEN_SECONDS = config('MCP_OAUTH_REFRESH_TOKEN_SECONDS', default=2592000, cast=int)
MCP_OAUTH_AUTH_CODE_SECONDS = config('MCP_OAUTH_AUTH_CODE_SECONDS', default=300, cast=int)
MCP_OAUTH_REQUEST_SECONDS = config('MCP_OAUTH_REQUEST_SECONDS', default=600, cast=int)
MCP_DELEGATED_JWT_SECONDS = config('MCP_DELEGATED_JWT_SECONDS', default=60, cast=int)

BACKUP_DIR = config('BACKUP_DIR', default=str(BASE_DIR / 'backups/postgres'))
BACKUP_LOG_DIR = config('BACKUP_LOG_DIR', default=str(BASE_DIR / 'backups/logs'))
BACKUP_MIN_BYTES = config('BACKUP_MIN_BYTES', default=1024, cast=int)
BACKUP_UPLOAD_AFTER_CREATE = config('BACKUP_UPLOAD_AFTER_CREATE', default=True, cast=bool)
BACKUP_REMOTE_DIR = config('BACKUP_REMOTE_DIR', default='')
BACKUP_RCLONE_REMOTE = config('BACKUP_RCLONE_REMOTE', default='')
BACKUP_RSYNC_TARGET = config('BACKUP_RSYNC_TARGET', default='')
BACKUP_SCP_TARGET = config('BACKUP_SCP_TARGET', default='')
SCHEDULED_JOBS_ALERT_WEBHOOK_URL = config('SCHEDULED_JOBS_ALERT_WEBHOOK_URL', default='')
SCHEDULED_JOBS_MARKET_MAX_AGE_DAYS = config('SCHEDULED_JOBS_MARKET_MAX_AGE_DAYS', default=2, cast=int)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'money',
    'investments.apps.InvestmentsConfig',
    'mcp_gateway.apps.McpGatewayConfig',
    'ops.apps.OpsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'money.middleware.OneCSyncRequestMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'money.middleware.SuppressApiAuthenticateHeaderMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='djangolk'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432', cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ]
}

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', 
    default='http://localhost:8080,http://localhost:3000',
    cast=csv_list
)
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=True, cast=bool)

AI_DEFAULT_PROVIDER = config('AI_DEFAULT_PROVIDER', default='openrouter')
AI_OPENROUTER_API_KEY = config('AI_OPENROUTER_API_KEY', default='')
AI_OPENROUTER_MODEL = config('AI_OPENROUTER_MODEL', default='google/gemini-2.5-flash')
AI_OPENROUTER_BASE_URL = config(
    'AI_OPENROUTER_BASE_URL',
    default='https://openrouter.ai/api/v1/chat/completions',
)
AI_OPENROUTER_SITE_URL = config('AI_OPENROUTER_SITE_URL', default='')
AI_OPENROUTER_APP_NAME = config('AI_OPENROUTER_APP_NAME', default='djangolk')
AI_OPENAI_API_KEY = config('AI_OPENAI_API_KEY', default='')
AI_OPENAI_TRANSCRIBE_MODEL = config('AI_OPENAI_TRANSCRIBE_MODEL', default='gpt-4o-mini-transcribe')
AI_OPENAI_TRANSCRIBE_BASE_URL = config(
    'AI_OPENAI_TRANSCRIBE_BASE_URL',
    default='https://api.openai.com/v1/audio/transcriptions',
)
AI_OPENAI_TRANSCRIBE_LANGUAGE = config('AI_OPENAI_TRANSCRIBE_LANGUAGE', default='ru')
AI_OPENAI_TRANSCRIBE_PROMPT = config('AI_OPENAI_TRANSCRIBE_PROMPT', default='')
AI_ALLOW_RULE_BASED_FALLBACK = config('AI_ALLOW_RULE_BASED_FALLBACK', default=True, cast=bool)
AI_TELEGRAM_BOT_SECRET = config('AI_TELEGRAM_BOT_SECRET', default='')
AI_TELEGRAM_BOT_TOKEN = config('AI_TELEGRAM_BOT_TOKEN', default='')
AI_TELEGRAM_API_BASE_URL = config('AI_TELEGRAM_API_BASE_URL', default='https://api.telegram.org')
AI_DUPLICATE_WINDOW_SECONDS = config('AI_DUPLICATE_WINDOW_SECONDS', default=600, cast=int)

INVESTMENT_PRICE_PROVIDER = config('INVESTMENT_PRICE_PROVIDER', default='auto')
INVESTMENT_PRICE_PROVIDER_BASE_URL = config(
    'INVESTMENT_PRICE_PROVIDER_BASE_URL',
    default='https://api.coingecko.com/api/v3/simple/price',
)
INVESTMENT_MOEX_PRICE_PROVIDER_BASE_URL = config(
    'INVESTMENT_MOEX_PRICE_PROVIDER_BASE_URL',
    default='https://iss.moex.com/iss',
)
INVESTMENT_MOEX_BOARD = config('INVESTMENT_MOEX_BOARD', default='TQBR')
INVESTMENT_PRICE_PROVIDER_TIMEOUT = config('INVESTMENT_PRICE_PROVIDER_TIMEOUT', default=10.0, cast=float)
INVESTMENT_FX_PROVIDER = config('INVESTMENT_FX_PROVIDER', default='cbr')
INVESTMENT_FX_PROVIDER_BASE_URL = config(
    'INVESTMENT_FX_PROVIDER_BASE_URL',
    default='https://www.cbr.ru/scripts/XML_daily.asp',
)
INVESTMENT_FX_PROVIDER_TIMEOUT = config('INVESTMENT_FX_PROVIDER_TIMEOUT', default=10.0, cast=float)

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

# Spectacular API docs settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'LK API',
    'DESCRIPTION': 'Автоматически сгенерированная документация REST API. Инвестиционный модуль не синхронизируется с 1С.',
    'VERSION': '1.0.0',
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'UserStatusEnum': [
            ('COMP', 'Компания'),
            ('PRIV', 'Частное лицо'),
        ],
        'AiAssistantStatusEnum': [
            'created',
            'preview',
            'needs_confirmation',
            'balance',
            'duplicate',
        ],
        'AiProcessedInputStatusEnum': [
            ('created', 'Created'),
            ('duplicate', 'Duplicate'),
        ],
    },
}
