# Generated by Django 4.1.2 on 2023-02-13 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGraphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tranfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('includeInBudget', models.BooleanField(default=False)),
                ('cashFlowItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem')),
                ('walletIn', models.ForeignKey(db_column='walletIn', on_delete=django.db.models.deletion.PROTECT, related_name='walletIn', to='money.wallet')),
                ('walletOut', models.ForeignKey(db_column='walletOut', on_delete=django.db.models.deletion.PROTECT, related_name='walletOut', to='money.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('includeInBudget', models.BooleanField(default=False)),
                ('cashFlowItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('includeInBudget', models.BooleanField(default=False)),
                ('cashFlowItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amountOfMonts', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('cashFlowItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem')),
            ],
        ),
    ]
