# Generated by Django 4.1.2 on 2023-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowitem',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
