# Generated by Django 4.1.2 on 2023-02-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_cashflowitem_name_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetgraphic',
            name='budgetDocument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='money.budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowitem',
            name='code',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='code',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cashflowitem',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
