# Generated by Django 4.1.2 on 2023-02-20 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_budgetgraphic_budgetdocument_cashflowitem_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('includeInBudget', models.BooleanField(default=False)),
                ('cashFlowItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem')),
                ('walletIn', models.ForeignKey(db_column='walletIn', on_delete=django.db.models.deletion.PROTECT, related_name='walletIn', to='money.wallet')),
                ('walletOut', models.ForeignKey(db_column='walletOut', on_delete=django.db.models.deletion.PROTECT, related_name='walletOut', to='money.wallet')),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Tranfer',
        ),
    ]
