# Generated by Django 4.1.2 on 2023-08-23 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_transfer_alter_budget_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, null=True, unique=True)),
                ('name', models.CharField(max_length=25, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='number',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenditure',
            name='number',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='number',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='money.project'),
            preserve_default=False,
        ),
    ]
