# Generated by Django 4.1.2 on 2023-10-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0005_project_budget_number_expenditure_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="includeInBudget",
        ),
        migrations.AddField(
            model_name="cashflowitem",
            name="IncludeInBudget",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wallet",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
