# Generated by Django 4.1.2 on 2023-10-13 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0006_remove_receipt_includeinbudget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=9)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False)),
                ("isTransfer", models.BooleanField(default=False)),
                ("amountMounth", models.DecimalField(decimal_places=0, max_digits=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("dateStart", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cashFlowItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.cashflowitem",
                    ),
                ),
                (
                    "walletIn",
                    models.ForeignKey(
                        db_column="walletIn",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="APwalletIn",
                        to="money.wallet",
                    ),
                ),
                (
                    "walletOut",
                    models.ForeignKey(
                        db_column="walletOut",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="APwalletOut",
                        to="money.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="budget",
            name="type_of_budget",
            field=models.BooleanField(
                choices=[(True, "Приход"), (False, "Расход")], default=False
            ),
        ),
        migrations.CreateModel(
            name="TransferGraphic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateStart", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transferDocument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="money.transfer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenditureGraphic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateStart", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expenditureDocument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="money.expenditure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoPaymentGraphic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateStart", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "autoPaymentsDocument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="money.autopayment",
                    ),
                ),
            ],
        ),
    ]
