# Generated by Django 4.1.2 on 2023-10-16 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0007_autopayment_budget_type_of_budget_transfergraphic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autopaymentgraphic",
            old_name="autoPaymentsDocument",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="budgetgraphic",
            old_name="budgetDocument",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="expendituregraphic",
            old_name="expenditureDocument",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="transfergraphic",
            old_name="transferDocument",
            new_name="document",
        ),
    ]
