# Generated by Django 4.1.2 on 2023-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_rename_autopaymentsdocument_autopaymentgraphic_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amountOfMonts',
            new_name='amountMounth',
        ),
        migrations.AlterField(
            model_name='autopayment',
            name='amountMounth',
            field=models.IntegerField(),
        ),
    ]
