# Generated by Django 4.1.2 on 2023-10-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_rename_amountofmonts_budget_amountmounth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.project'),
        ),
    ]
