# Generated by Django 4.1.2 on 2023-10-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_alter_budget_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autopayment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='autopayment',
            name='cashFlowItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
        migrations.AlterField(
            model_name='autopayment',
            name='walletIn',
            field=models.ForeignKey(db_column='walletIn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='APwalletIn', to='money.wallet'),
        ),
        migrations.AlterField(
            model_name='autopayment',
            name='walletOut',
            field=models.ForeignKey(db_column='walletOut', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='APwalletOut', to='money.wallet'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cashFlowItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='cashFlowItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.wallet'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cashFlowItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.wallet'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cashFlowItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='walletIn',
            field=models.ForeignKey(db_column='walletIn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='walletIn', to='money.wallet'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='walletOut',
            field=models.ForeignKey(db_column='walletOut', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='walletOut', to='money.wallet'),
        ),
    ]
