# Generated by Django 4.1.2 on 2023-10-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_alter_autopayment_options_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='money.cashflowitem'),
        ),
    ]
