# Generated by Django 4.1.2 on 2023-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_cashflowitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowitem',
            name='IncludeInBudget',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
