# Generated by Django 4.1.2 on 2023-10-23 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0013_alter_cashflowitem_includeinbudget"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowOfFunds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.DateTimeField()),
                (
                    "type_of_document",
                    models.IntegerField(
                        choices=[
                            (1, "AutoPayment"),
                            (2, "Transfer"),
                            (3, "Receipt"),
                            (4, "Expenditure"),
                        ]
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cashFlowItem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.cashflowitem",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetIncome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.DateTimeField()),
                (
                    "type_of_document",
                    models.IntegerField(choices=[(3, "Receipt"), (5, "Budget")]),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cashFlowItem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.cashflowitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.DateTimeField()),
                (
                    "type_of_document",
                    models.IntegerField(
                        choices=[
                            (1, "AutoPayment"),
                            (2, "Transfer"),
                            (4, "Expenditure"),
                            (5, "Budget"),
                        ]
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cashFlowItem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.cashflowitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.project",
                    ),
                ),
            ],
        ),
    ]
