# Generated by Django 4.1.2 on 2023-10-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0014_flowoffunds_budgetincome_budgetexpense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autopayment",
            old_name="amountMounth",
            new_name="amountMonth",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="amountMounth",
            new_name="amountMonth",
        ),
        migrations.AlterField(
            model_name="cashflowitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="money.cashflowitem",
            ),
        ),
    ]
