# Generated by Django 4.1.2 on 2023-10-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_rename_amountmounth_autopayment_amountmonth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowoffunds',
            options={'verbose_name_plural': 'Flow of funds'},
        ),
    ]
