# Generated by Django 4.1.2 on 2024-10-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0016_alter_flowoffunds_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopayment",
            name="cashFlowItem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="money.cashflowitem",
            ),
        ),
        migrations.AlterField(
            model_name="autopayment",
            name="walletIn",
            field=models.ForeignKey(
                blank=True,
                db_column="walletIn",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="APwalletIn",
                to="money.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="autopayment",
            name="walletOut",
            field=models.ForeignKey(
                blank=True,
                db_column="walletOut",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="APwalletOut",
                to="money.wallet",
            ),
        ),
    ]
