# Generated by Django 4.1.2 on 2025-08-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0017_alter_autopayment_cashflowitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='autopayment',
            old_name='amountMonth',
            new_name='amount_month',
        ),
        migrations.RenameField(
            model_name='autopayment',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='autopayment',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='autopayment',
            old_name='isTransfer',
            new_name='is_transfer',
        ),
        migrations.RenameField(
            model_name='autopaymentgraphic',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='amountMonth',
            new_name='amount_month',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='budgetexpense',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='budgetgraphic',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='budgetincome',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='cashflowitem',
            old_name='IncludeInBudget',
            new_name='include_in_budget',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='includeInBudget',
            new_name='include_in_budget',
        ),
        migrations.RenameField(
            model_name='expendituregraphic',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='flowoffunds',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='cashFlowItem',
            new_name='cash_flow_item',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='includeInBudget',
            new_name='include_in_budget',
        ),
        migrations.RenameField(
            model_name='transfergraphic',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='autopayment',
            name='walletIn',
        ),
        migrations.RemoveField(
            model_name='autopayment',
            name='walletOut',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='walletIn',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='walletOut',
        ),
        migrations.AddField(
            model_name='autopayment',
            name='wallet_in',
            field=models.ForeignKey(blank=True, db_column='wallet_in', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_wallet_in', to='money.wallet'),
        ),
        migrations.AddField(
            model_name='autopayment',
            name='wallet_out',
            field=models.ForeignKey(blank=True, db_column='wallet_out', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_wallet_out', to='money.wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet_in',
            field=models.ForeignKey(db_column='wallet_in', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_in', to='money.wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet_out',
            field=models.ForeignKey(db_column='wallet_out', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_out', to='money.wallet'),
        ),
    ]
