# Generated by Django 4.1.2 on 2025-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0018_alter_expenditure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetincome',
            name='document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowoffunds',
            name='document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
