# Generated by Django 4.1.2 on 2025-08-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0019_add_document_id_to_registers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autopayment',
            options={'ordering': ['-date'], 'verbose_name': 'Автоплатеж', 'verbose_name_plural': 'Автоплатежи'},
        ),
        migrations.AlterModelOptions(
            name='autopaymentgraphic',
            options={'ordering': ['date_start'], 'verbose_name': 'График автоплатежа', 'verbose_name_plural': 'Графики автоплатежей'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-date'], 'verbose_name': 'Бюджет', 'verbose_name_plural': 'Бюджеты'},
        ),
        migrations.AlterModelOptions(
            name='budgetexpense',
            options={'ordering': ['-period'], 'verbose_name': 'Расход бюджета', 'verbose_name_plural': 'Расходы бюджета'},
        ),
        migrations.AlterModelOptions(
            name='budgetgraphic',
            options={'ordering': ['date_start'], 'verbose_name': 'График бюджета', 'verbose_name_plural': 'Графики бюджетов'},
        ),
        migrations.AlterModelOptions(
            name='budgetincome',
            options={'ordering': ['-period'], 'verbose_name': 'Доход бюджета', 'verbose_name_plural': 'Доходы бюджета'},
        ),
        migrations.AlterModelOptions(
            name='cashflowitem',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Статья движения средств', 'verbose_name_plural': 'Статьи движения средств'},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-date'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='expendituregraphic',
            options={'ordering': ['date_start'], 'verbose_name': 'График расхода', 'verbose_name_plural': 'Графики расходов'},
        ),
        migrations.AlterModelOptions(
            name='flowoffunds',
            options={'ordering': ['-period'], 'verbose_name': 'Движение средств', 'verbose_name_plural': 'Движения средств'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date'], 'verbose_name': 'Приход', 'verbose_name_plural': 'Приходы'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date'], 'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterModelOptions(
            name='transfergraphic',
            options={'ordering': ['date_start'], 'verbose_name': 'График перевода', 'verbose_name_plural': 'Графики переводов'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
    ]
