# Generated by Django 4.1.2 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0020_alter_autopayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopayment',
            name='amount_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='include_in_budget',
            field=models.BooleanField(default=True),
        ),
    ]
