# Generated by Django 4.1.2 on 2026-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0030_aipendingconfirmation_context_payload"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(fields=["-date"], name="m_autopay_date_idx"),
        ),
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(fields=["date_start"], name="m_autopay_start_idx"),
        ),
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="m_autopay_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(
                fields=["wallet_out", "date_start"], name="m_autopay_out_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(
                fields=["wallet_in", "date_start"], name="m_autopay_in_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopayment",
            index=models.Index(
                fields=["cash_flow_item", "date_start"], name="m_autopay_cfi_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["-date"], name="m_budget_date_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["date_start"], name="m_budget_start_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="m_budget_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["type_of_budget", "cash_flow_item", "date_start"],
                name="m_budget_type_cfi_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["project", "date_start"], name="m_budget_project_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetexpense",
            index=models.Index(fields=["-period"], name="m_bexp_period_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetexpense",
            index=models.Index(
                fields=["cash_flow_item", "-period"], name="m_bexp_cfi_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetexpense",
            index=models.Index(
                fields=["project", "-period"], name="m_bexp_project_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetexpense",
            index=models.Index(
                fields=["type_of_document", "document_id"], name="m_bexp_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetincome",
            index=models.Index(fields=["-period"], name="m_binc_period_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetincome",
            index=models.Index(
                fields=["cash_flow_item", "-period"], name="m_binc_cfi_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetincome",
            index=models.Index(
                fields=["project", "-period"], name="m_binc_project_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetincome",
            index=models.Index(
                fields=["type_of_document", "document_id"], name="m_binc_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenditure",
            index=models.Index(fields=["-date"], name="m_exp_date_idx"),
        ),
        migrations.AddIndex(
            model_name="expenditure",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="m_exp_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenditure",
            index=models.Index(
                fields=["wallet", "-date"], name="m_exp_wallet_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenditure",
            index=models.Index(
                fields=["cash_flow_item", "-date"], name="m_exp_cfi_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowoffunds",
            index=models.Index(fields=["-period"], name="m_flow_period_idx"),
        ),
        migrations.AddIndex(
            model_name="flowoffunds",
            index=models.Index(
                fields=["wallet", "-period"], name="m_flow_wallet_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowoffunds",
            index=models.Index(
                fields=["cash_flow_item", "-period"], name="m_flow_cfi_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowoffunds",
            index=models.Index(
                fields=["type_of_document", "document_id"], name="m_flow_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["-date"], name="m_receipt_date_idx"),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="m_receipt_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["wallet", "-date"], name="m_receipt_wallet_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["cash_flow_item", "-date"], name="m_receipt_cfi_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(fields=["-date"], name="m_transfer_date_idx"),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="m_transfer_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["wallet_out", "-date"], name="m_transfer_out_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["wallet_in", "-date"], name="m_transfer_in_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["cash_flow_item", "-date"], name="m_transfer_cfi_date_idx"
            ),
        ),
    ]
