# Generated by Django 4.1.2 on 2026-05-10 12:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("money", "0030_aipendingconfirmation_context_payload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("crypto", "Криптовалюта"), ("stock", "Акция")],
                        default="crypto",
                        max_length=20,
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_symbol",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("quote_currency", models.CharField(default="USD", max_length=10)),
                ("precision", models.PositiveSmallIntegerField(default=8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Финансовый инструмент",
                "verbose_name_plural": "Финансовые инструменты",
                "ordering": ["type", "ticker"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("exchange", "Биржа"),
                            ("broker", "Брокер"),
                            ("cold_wallet", "Холодный кошелек"),
                            ("manual", "Ручной счет"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=10)),
                ("hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Инвестиционный счет",
                "verbose_name_plural": "Инвестиционные счета",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_currency", models.CharField(default="RUB", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="money.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвестиционный портфель",
                "verbose_name_plural": "Инвестиционные портфели",
                "ordering": ["user", "-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=12)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("buy", "Покупка"),
                            ("sell", "Продажа"),
                            ("transfer_instrument", "Перевод инструмента"),
                            ("correction", "Корректировка"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="RUB", max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                ("amount_currency", models.CharField(default="RUB", max_length=10)),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "fx_rate_to_rub",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=24
                    ),
                ),
                ("fee_currency", models.CharField(default="RUB", max_length=10)),
                (
                    "fee_rub",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=200)),
                ("deleted", models.BooleanField(default=False)),
                ("posted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="investments.investmentaccount",
                    ),
                ),
                (
                    "account_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="investments.investmentaccount",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="investments.instrument",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="investments.investmentportfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвестиционная операция",
                "verbose_name_plural": "Инвестиционные операции",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="investmentaccount",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="investments.investmentportfolio",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                fields=("type", "ticker"), name="uniq_instrument_type_ticker"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentportfolio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="uniq_default_investment_portfolio_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentaccount",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "name"),
                name="uniq_investment_account_portfolio_name",
            ),
        ),
    ]
