# Generated by Django 4.1.2 on 2026-05-10 15:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentPriceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=24)),
                ("price_currency", models.CharField(default="USD", max_length=10)),
                (
                    "fx_rate_to_rub",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("price_rub", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="investments.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок цены инструмента",
                "verbose_name_plural": "Снимки цен инструментов",
                "ordering": ["-captured_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="instrumentpricesnapshot",
            index=models.Index(
                fields=["instrument", "-captured_at"],
                name="investments_instrum_b14bbd_idx",
            ),
        ),
    ]
