# Generated by Codex on 2026-05-10

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_instrumentpricesnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRateSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("base_currency", models.CharField(max_length=10)),
                ("quote_currency", models.CharField(default="RUB", max_length=10)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Снимок валютного курса",
                "verbose_name_plural": "Снимки валютных курсов",
                "ordering": ["-captured_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fxratesnapshot",
            index=models.Index(
                fields=["base_currency", "quote_currency", "-captured_at"],
                name="investments_base_cu_dee1d6_idx",
            ),
        ),
    ]
