# Generated by Codex on 2026-05-11

from decimal import Decimal
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_fxratesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentTargetAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_allocations",
                        to="investments.instrument",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_allocations",
                        to="investments.investmentportfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Целевая доля инструмента",
                "verbose_name_plural": "Целевые доли инструментов",
                "ordering": ["portfolio", "instrument__ticker"],
            },
        ),
        migrations.AddConstraint(
            model_name="investmenttargetallocation",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "instrument"),
                name="uniq_target_allocation_portfolio_instrument",
            ),
        ),
    ]
