# Generated by Django 4.1.2 on 2026-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0009_split_operation_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="investmentoperation",
            index=models.Index(
                fields=["portfolio", "-date"], name="inv_op_portfolio_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentoperation",
            index=models.Index(
                fields=["account", "-date"], name="inv_op_account_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentoperation",
            index=models.Index(
                fields=["instrument", "-date"], name="inv_op_instr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentoperation",
            index=models.Index(
                fields=["deleted", "posted", "-date"], name="inv_op_state_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentoperation",
            index=models.Index(
                fields=["operation_type", "-date"], name="inv_op_type_date_idx"
            ),
        ),
    ]
