# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_investmentoperation_inv_op_portfolio_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(
                choices=[
                    ('crypto', 'Криптовалюта'),
                    ('stock', 'Акция'),
                    ('bond', 'Облигация'),
                ],
                default='crypto',
                max_length=20,
            ),
        ),
    ]
